import fs from "fs";
import path from "path";
import {
  Document,
  HeadingLevel,
  Packer,
  PageBreak,
  Paragraph,
  TextRun,
} from "docx";

function sourceLines(content) {
  const lines = content.split(/\r?\n/);
  if (lines.at(-1) === "") lines.pop();
  return lines;
}

/**
 * Generate a file-aware Word archive and return its verified output metadata.
 */
export async function generateWordDoc(filePath, sourceFiles, options = {}) {
  const linesPerPage = options.linesPerPage ?? 50;
  const pure = options.pure ?? false;
  const outputPath = path.resolve(filePath);
  const paragraphs = [
    new Paragraph({
      text: "Source Code Archive",
      heading: HeadingLevel.TITLE,
    }),
    new Paragraph(`Files: ${sourceFiles.length}`),
  ];
  let pageLineCount = 0;

  for (const sourceFile of sourceFiles) {
    paragraphs.push(new Paragraph({
      text: sourceFile.path,
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: paragraphs.length > 2,
    }));
    if (!pure) {
      paragraphs.push(new Paragraph(`${sourceFile.lineCount} lines · ${sourceFile.byteCount} bytes`));
      paragraphs.push(new Paragraph(`SHA-256: ${sourceFile.sha256}`));
    }

    for (const line of sourceLines(sourceFile.content)) {
      paragraphs.push(new Paragraph({
        children: [new TextRun({
          text: line.length > 0 ? line : " ",
          font: "Consolas",
          size: 18,
        })],
        spacing: { after: 0, line: 240 },
      }));
      pageLineCount += 1;

      if (pageLineCount === linesPerPage) {
        paragraphs.push(new Paragraph({ children: [new PageBreak()] }));
        pageLineCount = 0;
      }
    }
  }

  const document = new Document({
    creator: "code-to-docx",
    title: "Source Code Archive",
    description: "A file-aware source code archive generated by code-to-docx.",
    sections: [{ properties: {}, children: paragraphs }],
  });

  await fs.promises.mkdir(path.dirname(outputPath), { recursive: true });
  const buffer = await Packer.toBuffer(document);
  await fs.promises.writeFile(outputPath, buffer);
  const stat = await fs.promises.stat(outputPath);

  if (stat.size === 0) {
    throw new Error(`Generated document is empty: ${outputPath}`);
  }

  return { path: outputPath, bytes: stat.size };
}
